# Generated by Django 5.2.1 on 2025-05-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_gallery_size_specification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'proudct images'},
        ),
    ]
