# Generated by Django 5.2.1 on 2025-06-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=12),
        ),
    ]
