# Generated by Django 5.2.1 on 2025-06-14 21:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cart_shipping_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Cart ID'),
        ),
    ]
