# Generated by Django 5.2.1 on 2025-06-15 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Cart ID'),
        ),
    ]
