# Generated by Django 5.2.1 on 2025-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_cartorderitem_coupon_cartorderitem_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
