# Generated by Django 5.2.1 on 2025-07-10 22:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_notifications_user_alter_notifications_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WisList',
            new_name='WishList',
        ),
    ]
