# Generated by Django 5.2.1 on 2025-05-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ful_name',
            new_name='full_name',
        ),
    ]
