# Generated by Django 5.2.1 on 2025-05-18 19:15

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_userprofile_full_name_userprofile_ful_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ful_name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, length=10, max_length=12, prefix='', unique=True),
        ),
    ]
