# Generated by Django 5.2.1 on 2025-05-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_rename_ful_name_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='ful_name',
        ),
    ]
