# Generated by Django 5.2.1 on 2025-05-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_rename_full_name_userprofile_ful_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ful_name',
            new_name='full_name',
        ),
    ]
