# Generated by Django 5.2.1 on 2025-05-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_rename_ful_name_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
