# Generated by Django 5.2.1 on 2025-05-28 20:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_user_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, length=10, max_length=10, prefix='', unique=True),
        ),
    ]
